# Generated by Django 6.0.4 on 2026-04-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PontoDeColeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Local')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço Completo')),
                ('materiais_aceitos', models.TextField(help_text='Ex: Pilhas, Baterias, Óleo de Cozinha, Eletrônicos', verbose_name='Materiais Aceitos')),
            ],
        ),
    ]
